///////////////////////////////////////////////////////////
//  SenhasTransacao.cs
//  Implementation of the Class SenhasTransacao
//  Generated by Enterprise Architect
//  Created on:      30-set-2014 09:57:54
//  Original author: f0030117
///////////////////////////////////////////////////////////

using System.ComponentModel.DataAnnotations;

namespace Ailos.SOA.CardAutorization.DTO.Common
{
    /// <summary>
    /// Objeto que representa um conjunto de senhas para transação na aplicação.
    /// </summary>
    public class SenhasTransacao
    {
        // Declaração das variáveis privadas
        private string _Letras;

        private string _Senha;

        /// <summary>
        /// Inicia uma nova instância do objeto.
        /// </summary>
        public SenhasTransacao()
        {
        }

        /// <summary>
        /// Senha de letras. (obrigatório)
        /// </summary>
        [Required(ErrorMessageResourceName = "FieldRequired", ErrorMessageResourceType = typeof(ResultMessages))]
        public string Letras
        {
            get
            {
                return _Letras;
            }
            set
            {
                _Letras = value;
            }
        }

        /// <summary>
        /// Senha numérica. (obrigatório)
        /// </summary>
        [Required(ErrorMessageResourceName = "FieldRequired", ErrorMessageResourceType = typeof(ResultMessages))]
        public string Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                _Senha = value;
            }
        }
    }//end SenhasTransacao
}//end namespace Ailos.MobileBank.Models